language: python
python:
  - "2.7_with_system_site_packages"
  - "3.5"
# command to install dependencies
install: 
  - "pip install numpy"
  - "pip install scipy"
  - "pip install matplotlib"
  - "pip install six"
  - "pip install nose"
# command to run tests
script: pytest
