language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install: 
  - "pip install --only-binary=numpy,scipy numpy scipy"
  - "pip install matplotlib"
  - "pip install six"
  - "pip install nose"
# command to run tests
script: nose
