sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
  - "sudo apt-get install libatlas-base-dev gfortran"
  - "mkdir $HOME/.matplotlib"
  - "echo 'backend: TkAgg' > $HOME/.matplotlib/matplotlibrc"
# command to install dependencies
install: 
#  - "pip install numpy"
  - "pip install scipy"
  - "pip install pandas"
  - "pip install matplotlib"
  - "pip install six"
  - "pip install pytest"
  - "pip install pytest-pep8"
  - "pip install pytest-cov"
  - "pip install python-coveralls"
# command to run tests
script: py.test --cov=sci_analysis --cov-report term-missing
after_sucess:
  - coveralls
